Traceback (most recent call last):
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/aymeric/anaconda3/envs/analyse_tweets/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
role_tree = users.groupby(["User_status", "User_role2","User_role"]).agg(n=('user_id', 'count'))
role_tree_style = individual_role_tree.style.format(precision=0, na_rep='')
#role_tree_style.to_html()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_11242/283382819.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mrole_tree[0m [0;34m=[0m [0musers[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0;34m[[0m[0;34m"User_status"[0m[0;34m,[0m [0;34m"User_role2"[0m[0;34m,[0m[0;34m"User_role"[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0magg[0m[0;34m([0m[0mn[0m[0;34m=[0m[0;34m([0m[0;34m'user_id'[0m[0;34m,[0m [0;34m'count'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mrole_tree_style[0m [0;34m=[0m [0mindividual_role_tree[0m[0;34m.[0m[0mstyle[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mprecision[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0mna_rep[0m[0;34m=[0m[0;34m''[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;31m#role_tree_style.to_html()[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'individual_role_tree' is not defined
NameError: name 'individual_role_tree' is not defined

